---
- name: Actualizar rhel
  hosts: "{{ nodo }}"
  become: yes

  tasks:
  #realizar actualizacion de rhel la ultima disponible & instalar ngnx &levantar el servicio de ngnx & abrir  firewall puerto 80 tcp
  - name: Realizar actualizacion de rhel la ultima disponible
    ansible.builtin.package:
      name: '*'
      state: latest

  - name: Instalar ngnx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Levantar el servicio de ngnx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Abrir  firewall puerto 80 tcp
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
      immediate: true
