---
- name: Setup inicial en AWS para lanzar máquinas virtuales
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-1
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    security_group: my_security_group

  tasks:
    - name: Crear una VPC
      amazon.aws.ec2_vpc:
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        resource_tags:
          Name: my_vpc
      register: vpc

    - name: Crear un Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
      register: igw

    - name: Adjuntar Internet Gateway a la VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc_id }}"
        internet_gateway_id: "{{ igw.internet_gateway_id }}"
        region: "{{ aws_region }}"
        state: present

    - name: Crear una subred
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc_id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ aws_region }}"
        resource_tags:
          Name: my_subnet
      register: subnet

    - name: Crear una tabla de rutas
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.internet_gateway_id }}"
        associations:
          - subnet_id: "{{ subnet.subnet.id }}"
      register: route_table

    - name: Crear un grupo de seguridad
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: "Security group for EC2 instances"
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 443
            cidr_ip: 0.0.0.0/0
      register: group
